apiVersion: apps/v1
kind: Deployment
metadata:
  name: foo-deployment
spec:
  replicas: 1
  selector:
    matchLabels:
      app: foo
  template:
    metadata:
      labels:
        app: foo
    spec:
      containers:
      - name: foo-container
        image: my-python-app:latest
        imagePullPolicy: Never
        ports:
        - containerPort: 8000
          name: http
        - containerPort: 22
          name: ssh
---
kind: Service
apiVersion: v1
metadata:
  name: foo-service
spec:
  selector:
    app: foo
  ports:
  - protocol: TCP
    targetPort: 8000
    port: 8080
    name: http
  - protocol: TCP
    targetPort: 22
    port: 22
    name: ssh
  type: LoadBalancer
  externalIPs:
  - 10.1.1.9