apiVersion: apps/v1
kind: Deployment
metadata:
  name: foo-deployment
spec:
  replicas: 1
  selector:
    matchLabels:
      app: foo
  template:
    metadata:
      labels:
        app: foo
    spec:
      containers:
      - name: foo-container
        image: claritee/node-app:latest
        ports:
        - containerPort: 3000
          name: http
        - containerPort: 22
          name: ssh
---
kind: Service
apiVersion: v1
metadata:
  name: foo-service
spec:
  selector:
    app: foo
  ports:
  - protocol: TCP
    targetPort: 3000
    port: 80
    name: http
  - protocol: TCP
    targetPort: 22
    port: 22
    name: ssh
  type: LoadBalancer
  externalIPs:
  - 10.1.1.9