apiVersion: apps/v1
kind: Deployment
metadata:
  name: python-app-deployment
spec:
  replicas: 1
  selector:
    matchLabels:
      app: python-app
  template:
    metadata:
      labels:
        app: python-app
    spec:
      containers:
      - name: python-app-container
        image: claritee/python-app:latest
        ports:
        - containerPort: 8000
          name: http
        - containerPort: 22
          name: ssh
---
kind: Service
apiVersion: v1
metadata:
  name: python-app-service
spec:
  selector:
    app: python-app
  ports:
  - protocol: TCP
    targetPort: 8000
    port: 80
    name: http
  - protocol: TCP
    targetPort: 22
    port: 22
    name: ssh
  type: LoadBalancer
  externalIPs:
  - 10.1.1.8