apiVersion: apps/v1
kind: Deployment
metadata:
  name: python-app-deployment
spec:
  replicas: 1
  selector:
    matchLabels:
      app: python-app
  template:
    metadata:
      labels:
        app: python-app
    spec:
      containers:
      - name: python-app
        image: claritee/python-app:latest
        ports:
        - containerPort: 8000
          name: http
        - containerPort: 22
          name: ssh